clothes/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.add, name='add'),
    path('remove/<int:id>/', views.remove, name='remove'),
    path('pay/', views.pay, name='pay'),
    path('create_order/', views.create_order, name='create_order'),
    path('clear/', views.clear, name='clear'),
    path('', views.cart_detail, name='cart_detail')
]

clothes/clothes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clothes/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.product_info, name='product_info'),
    path('<str:category_slug>/<str:subcategory_slug>/', views.subcategory, name='subcategory')
]

clothes/cart/models.py
from django.db import models

# Create your models here.

clothes/main/models.py
from django.db import models
from django.urls import reverse 


class Category(models.Model):
    name = models.CharField(max_length=255,
                            unique=True)
    slug = models.SlugField(max_length=255,
                            unique=True)
    

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    

class SubCategory(models.Model):
    name = models.CharField(max_length=255,
                            unique=True)
    slug = models.SlugField(max_length=255,
                            unique=True)
    category = models.ForeignKey(Category,
                                 related_name='subcategories',
                                 on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


    def get_absolute_url(self):
        return reverse("main:subcategory", args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(SubCategory,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['created'])
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse("main:product_info", args=[self.id])
    

    def __str__(self):
        return self.name

class ProductSize(models.Model):
    SIZE_CHOICES = [
        ("XS", "Extra Small"),
        ("S", "Small"),
        ("M", "Medium"),
        ("L", "Large"),
        ("XL", "Extra Large"),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="sizes")
    size = models.CharField(max_length=3, choices=SIZE_CHOICES)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} - {self.size} ({self.stock} шт.)"
    

class Order(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    house = models.CharField(max_length=255)
    flat = models.IntegerField()
    email = models.EmailField(max_length=255)

    paid = models.BooleanField(default=False)
    sent = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product_size = models.ForeignKey(ProductSize, on_delete=models.DO_NOTHING)
    quantity = models.PositiveIntegerField(default=1)

clothes/cart/forms.py
from django import forms

from main.models import ProductSize, Order


class AddToCartForm(forms.Form):
    size = forms.ModelChoiceField(
        queryset=ProductSize.objects.none(),
        empty_label="Выберите размер"
    )

    def __init__(self, product, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['size'].queryset = product.sizes.all()

    
class CreateOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'city', 'street', 'house', 'flat', 'email']

clothes/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from .forms import AddToCartForm, CreateOrderForm
from main.models import OrderItem, Order, ProductSize
from .cart import Cart


@require_POST
def add(request, id):
    size = get_object_or_404(ProductSize, id=id)
    form = AddToCartForm(size.product, request.POST)
    if form.is_valid():
        size = form.cleaned_data['size']
        cart = Cart(request)
        cart.add(size)
    return redirect('main:product_info',
                    id = size.product.id)


@require_POST
def remove(request, id):
    size = get_object_or_404(ProductSize, id=id)
    cart = Cart(request)
    cart.remove(size)
    return redirect('cart:cart_detail')


@require_POST
def clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


@require_POST
def pay(request):
    cart = Cart(request)
    form = CreateOrderForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        for size_id, dict in cart.cart.items():
            size = get_object_or_404(ProductSize, id=int(size_id))
            if size.stock < dict['quantity']:
                return redirect('cart:cart_detail')
        
        order = Order.objects.create(
            name = cd['name'],
            surname = cd['surname'],
            city = cd['city'],
            street = cd['street'],
            house = cd['house'],
            flat = cd['flat'],
            email = cd['email']
        )
        for size_id, dict in cart.cart.items():
            size = get_object_or_404(ProductSize, id=int(size_id))
            OrderItem.objects.create(order=order, product_size=size, quantity=dict['quantity'])
    return redirect('cart:cart_detail')


@require_POST
def create_order(request):
    cart = Cart(request)
    cart_sum = 0
    for size_id, dict in cart.cart.items():
        size = get_object_or_404(ProductSize, id=int(size_id))
        for _ in range(int(dict['quantity'])):
            cart_sum += size.product.price

    return render(request,
                  'cart/create-order.html',
                  {'cart_sum': cart_sum})
    


def cart_detail(request):
    cart = Cart(request)
    sizes = []
    cart_sum = 0
    for size_id, dict in cart.cart.items():
        size = get_object_or_404(ProductSize, id=int(size_id))
        for _ in range(int(dict['quantity'])):
            sizes.append(size)
            cart_sum += size.product.price
        
    return render(request,
                  'cart/detail.html',
                  {'cart': sizes,
                   'cart_sum': cart_sum})

clothes/main/views.py
from django.shortcuts import render, get_object_or_404
import random

from .models import Product, Category, SubCategory


def index(request):
    all_products = []

    categories = Category.objects.all()

    for category in categories:
        subcategories = category.subcategories.all()
        for subcategory in subcategories:
            all_products.extend(subcategory.products.all())

    products = random.choices(all_products, k=3) if len(all_products) >= 3 else None

    return render(request,
                  'main/index/index.html',
                  {'products': products,
                   "categories": categories})


def subcategory(request, category_slug, subcategory_slug):
    sorted = request.GET.get('sorted')
    if not sorted:
        sorted = '-created'

    subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)

    products = subcategory.products.filter(available=True).order_by(sorted)

    showed_products = 9
    current_page = int(request.GET.get('page', 1))
    try:
        current_page_products = products[(showed_products) * (current_page - 1):(showed_products) * current_page]
    except IndexError:
        current_page_products = products[(showed_products) * (current_page - 1):len(products) + 1]
    if len(products) / showed_products % 1 == 0:
        pages = range(1, len(products) // showed_products + 1)
    else:
        pages = range(1, len(products) // showed_products + 2)
    counter_start = showed_products * (current_page - 1)

    return render(request,
                  'main/category/index.html',
                  {'products': products,
                   'counter_start': counter_start,
                   'current_page': current_page,
                   'pages': pages})


def product_info(request, id):
    product = get_object_or_404(Product, id=id)
    sizes = product.sizes.all()

    if request.method == "GET":
        return render(request,
                    'main/product/info.html',
                    {'product': product,
                    'sizes': sizes})

clothes/main/templates/cart/create-order.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Создать заказ{% endblock title %}

{% block content %}
    <form action="{% url "cart:pay" %}" method="POST">
        {% csrf_token %}
        <div class="order-form">
            <div class="section">
                <div class="input">
                    <label for="name">Имя</label>
                    <input type="text" name="name">
                </div>
                <div class="input">
                    <label for="surname">Фамилия</label>
                    <input type="text" name="surname">
                </div>
            </div>
            <div class="input">
                <label for="city">Город</label>
                <input type="text" name="city">
            </div>
            <div class="input">
                <label for="street">Улица</label>
                <input type="text" name="street">
            </div>
            <div class="section">
                <div class="input">
                    <label for="house">Дом</label>
                    <input type="text" name="house">
                </div>
                <div class="input">
                    <label for="flat">Квартира</label>
                    <input type="text" name="flat">
                </div>
            </div>
            <div class="input">
                <label for="email">Почта</label>
                <input type="email" name="email">
            </div>
            <button>
                ОПЛАТИТЬ {{ cart_sum }} €
            </button>
        </div>
    </form>
{% endblock content %}

clothes/main/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Корзина{% endblock title %}

{% block content %}
{% if cart %}
    {% for size in cart %}
        <form action="{% url 'cart:remove' id=size.id %}" method="POST">
            {% csrf_token %}
            <div class="cart-item">
                <div class="d-flex align-items-center gap-5">
                    <img class="cart-item-img" src="{{ size.product.image.url }}" width="130" height="130">
                    <p class="name">
                        {{ size.product.name }}
                    </p>
                    <p class="size">
                        {{ size.size }}
                    </p>
                </div>
                <div class="d-flex align-items-center gap-5">
                    <p class="price">
                        {{ size.product.price }} €
                    </p>
                    <button type="submit">
                        УДАЛИТЬ
                    </button>
                </div>
            </div>
        </form>
    {% endfor %}
    <form action="{% url 'cart:create_order' %}" method="POST">
        {% csrf_token %}
        <div class="order">
            <div class="cart-total">
                <div class="total">
                    TOTAL
                </div>
                <div class="d-flex justify-content-center align-items-center gap-5">
                    <p class="price">
                        {{ cart_sum }} €
                    </p>
                </div>
            </div>
            <button>
                ОПЛАТИТЬ
            </button>
        </div>
    </form>
{% else %}
    <div class="empty-cart">
        <h1>
            ВАША КОРЗИНА ПУСТА
        </h1>
    </div>
{% endif %}
{% endblock content %}