clothes/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:id>/', views.add, name='add'),
    path('remove/<int:id>/', views.remove, name='remove'),
    path('pay/', views.pay, name='pay'),
    path('create_order/', views.create_order, name='create_order'),
    path('clear/', views.clear, name='clear'),
    path('', views.cart_detail, name='cart_detail')
]

clothes/clothes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

clothes/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.product_info, name='product_info'),
    path('<str:category_slug>/<str:subcategory_slug>/', views.subcategory, name='subcategory')
]

clothes/main/models.py
from django.db import models
from django.urls import reverse 


class Category(models.Model):
    name = models.CharField(max_length=255,
                            unique=True)
    slug = models.SlugField(max_length=255,
                            unique=True)
    

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    

class SubCategory(models.Model):
    name = models.CharField(max_length=255,
                            unique=True)
    slug = models.SlugField(max_length=255,
                            unique=True)
    category = models.ForeignKey(Category,
                                 related_name='subcategories',
                                 on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


    def get_absolute_url(self):
        return reverse("main:subcategory", args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(SubCategory,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['created'])
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse("main:product_info", args=[self.id])
    

    def __str__(self):
        return self.name

class ProductSize(models.Model):
    SIZE_CHOICES = [
        ("XS", "Extra Small"),
        ("S", "Small"),
        ("M", "Medium"),
        ("L", "Large"),
        ("XL", "Extra Large"),
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="sizes")
    size = models.CharField(max_length=3, choices=SIZE_CHOICES)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} - {self.size} ({self.stock} шт.)"
    

class Order(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    house = models.CharField(max_length=255)
    flat = models.IntegerField()
    email = models.EmailField(max_length=255)

    paid = models.BooleanField(default=False)
    sent = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product_size = models.ForeignKey(ProductSize, on_delete=models.DO_NOTHING)
    quantity = models.PositiveIntegerField(default=1)

clothes/main/views.py
from django.shortcuts import render, get_object_or_404
import random

from .models import Product, Category, SubCategory


def index(request):
    all_products = []

    categories = Category.objects.all()

    for category in categories:
        subcategories = category.subcategories.all()
        for subcategory in subcategories:
            all_products.extend(subcategory.products.all())

    products = random.choices(all_products, k=3) if len(all_products) >= 3 else None

    return render(request,
                  'main/index/index.html',
                  {'products': products,
                   "categories": categories})


def subcategory(request, category_slug, subcategory_slug):
    sorted = request.GET.get('sorted')
    if not sorted:
        sorted = '-created'

    subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)

    products = subcategory.products.filter(available=True).order_by(sorted)

    showed_products = 9
    current_page = int(request.GET.get('page', 1))
    try:
        current_page_products = products[(showed_products) * (current_page - 1):(showed_products) * current_page]
    except IndexError:
        current_page_products = products[(showed_products) * (current_page - 1):len(products) + 1]
    if len(products) / showed_products % 1 == 0:
        pages = range(1, len(products) // showed_products + 1)
    else:
        pages = range(1, len(products) // showed_products + 2)
    counter_start = showed_products * (current_page - 1)

    return render(request,
                  'main/category/index.html',
                  {'products': products,
                   'counter_start': counter_start,
                   'current_page': current_page,
                   'pages': pages})


def product_info(request, id):
    product = get_object_or_404(Product, id=id)
    sizes = product.sizes.all()

    if request.method == "GET":
        return render(request,
                    'main/product/info.html',
                    {'product': product,
                    'sizes': sizes})

clothes/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{% block title %}Lorem Ipsum{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="sticky-top header">
            <ul class="nav-list container">
                <li class="nav-item">
                    <a href="{% url "main:index" %}">
                        <div class="logo">
                            <h1>
                                Lorem Ipsum
                            </h1>
                        </div>
                    </a>
                </li>
                <li class="nav-item category-btn">
                    <a href="#">
                        <div class="">
                            <h1>
                                КАТЕГОРИИ
                            </h1>
                        </div>
                    </a>
                <div class="category-list">
                    <ul>
                    {% for category in categories %}
                        <li class="category-item">
                            <div class="category-choice">{{ category.name }}
                                <div class="subcategory-list">
                                    <ul>
                                        {% for subcategory in category.subcategories.all %}
                                            <li>
                                                <a href="{{ subcategory.get_absolute_url}}">
                                                    {{ subcategory.name }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                </li>
                <li class="nav-item">
                    <a href="{% url "cart:cart_detail" %}">
                        <div class="">
                            <h1>
                                КОРЗИНА
                            </h1>
                        </div>
                    </a>
                </li>
            </ul>
        <div class="stripe">

        </div>
    </header> 
    <div class="container fade-in">
        {% block content %}{% endblock content %}
    </div>
    <footer>
        <h1>
            Lorem Ipsum
        </h1>
        <div>

        </div>
        <div>
            
        </div>
    </footer>
    <script src={% static 'js/script.js' %}></script>
</body>
</html>